"""add thumbnail_url to product_images

Revision ID: 2abc716c1174
Revises: 60bb2dffd8dd
Create Date: 2026-06-20 15:48:56.621974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2abc716c1174'
down_revision: Union[str, None] = '60bb2dffd8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'thumbnail_url')
    # ### end Alembic commands ###