"""add_indexes

Revision ID: 60bb2dffd8dd
Revises: ca49cffd1e20
Create Date: 2026-06-06 13:28:52.860401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60bb2dffd8dd'
down_revision: Union[str, None] = 'ca49cffd1e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_customer_email', 'orders', ['customer_email'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_is_featured', 'products', ['is_featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_is_featured', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_customer_email', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    # ### end Alembic commands ###