"""add mk translation fields to products and categories

Revision ID: bd87438d3449
Revises: 2abc716c1174
Create Date: 2026-06-20 17:00:36.100216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd87438d3449'
down_revision: Union[str, None] = '2abc716c1174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_mk', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('description_mk', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('name_mk', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('description_mk', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_mk')
    op.drop_column('products', 'name_mk')
    op.drop_column('categories', 'description_mk')
    op.drop_column('categories', 'name_mk')
    # ### end Alembic commands ###